services:
  - type: web
    name: sistema-api
    env: docker
    region: frankfurt # You can change this to any valid region
    dockerfilePath: ./sistema back-end/Dockerfile
    dockerContext: ./sistema back-end
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
